// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/about.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var about_default = defineTool({
  name: "about_dose_academy",
  title: "About DOSE Academy",
  description: "Returns a short overview of DOSE Academy \u2014 an ADHD support app for teens (ages 10\u201317) with four core tools: SPARK, WAVE, RSD, and Squad Focus.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [
      {
        type: "text",
        text: [
          "DOSE Academy is a calm, teen-friendly ADHD support app (ages 10\u201317).",
          "",
          "Core tools:",
          "\u2022 SPARK \u2014 5-step tap-only emotional reset wizard.",
          "\u2022 WAVE \u2014 Pomodoro-style focus timer built for task paralysis.",
          "\u2022 RSD \u2014 Rejection-sensitivity intervention that validates first, then reframes.",
          "\u2022 Squad Focus \u2014 Body-doubling with ambient peers or invited squads.",
          "",
          "Tone: non-judgmental, affirming, never clinical or shaming."
        ].join("\n")
      }
    ]
  })
});

// src/lib/mcp/tools/list-tools.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var TOOLS = [
  {
    key: "spark",
    name: "SPARK",
    purpose: "5-step emotional reset wizard for overwhelm or big feelings.",
    path: "/spark"
  },
  {
    key: "wave",
    name: "WAVE",
    purpose: "Pomodoro focus timer designed to break task paralysis.",
    path: "/wave/setup"
  },
  {
    key: "rsd",
    name: "RSD",
    purpose: "Rejection-sensitivity intervention: validate, stabilize, decode.",
    path: "/rsd"
  },
  {
    key: "squad",
    name: "Squad Focus",
    purpose: "Body-doubling with ambient peers or an invited squad.",
    path: "/squad"
  },
  {
    key: "ignite",
    name: "IGNITE",
    purpose: "AI task activation \u2014 breaks tasks into minimal observable actions.",
    path: "/ignite"
  }
];
var list_tools_default = defineTool2({
  name: "list_dose_tools",
  title: "List DOSE tools",
  description: "Returns the DOSE Academy in-app tools (SPARK, WAVE, RSD, Squad, IGNITE) with a short purpose and app route for each.",
  inputSchema: {
    tool_key: z.enum(["spark", "wave", "rsd", "squad", "ignite"]).optional().describe("Optional: return details for a single tool only.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ tool_key }) => {
    const items = tool_key ? TOOLS.filter((t) => t.key === tool_key) : TOOLS;
    return {
      content: [{ type: "text", text: JSON.stringify(items, null, 2) }],
      structuredContent: { tools: items }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "dose-academy-mcp",
  title: "DOSE Academy",
  version: "0.1.0",
  instructions: "Read-only tools that describe DOSE Academy \u2014 an ADHD support app for teens \u2014 and its in-app tools (SPARK, WAVE, RSD, Squad, IGNITE). Use `about_dose_academy` for a high-level overview and `list_dose_tools` to enumerate the app's features.",
  tools: [about_default, list_tools_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
